from __future__ import annotations

from pathlib import Path
from typing import Protocol

from app.domain.clinical import EvalRunRequest, FieldExtractionResult, ReviewUpdate, VisionFallbackRequest
from app.domain.field_definitions import FieldDictionary
from app.domain.system_config import SystemConfig


class CaseRepository(Protocol):
    def list_cases(self) -> list[dict]: ...
    def get_case(self, case_id: str) -> dict: ...
    def case_exists_by_hash(self, file_hash: str) -> bool: ...
    def create_case(self, *, case_id: str, filename: str, file_hash: str, file_path: str) -> dict: ...
    def set_case_queued(self, case_id: str) -> None: ...
    def get_case_file_path(self, case_id: str) -> Path: ...
    def delete_case(self, case_id: str) -> int: ...
    def review_field(self, case_id: str, update: ReviewUpdate) -> dict: ...
    def diagnostics(self, case_id: str, config: SystemConfig) -> dict: ...
    def export_results(self, case_id: str) -> list[FieldExtractionResult]: ...
    def create_eval_run(self, request: EvalRunRequest) -> dict: ...
    def create_vision_fallback_request(self, case_id: str, request: VisionFallbackRequest) -> dict: ...


class FileStore(Protocol):
    def save_upload_bytes(self, *, filename: str, payload: bytes) -> tuple[str, Path]: ...


class TaskQueue(Protocol):
    def submit_case_processing(self, case_id: str) -> None: ...
    def process_case_now(self, case_id: str) -> None: ...


class CaseProcessor(Protocol):
    def process_case(self, case_id: str) -> None: ...


class RuntimeSettings(Protocol):
    @property
    def sync_pipeline(self) -> bool: ...


class FieldDictionaryProvider(Protocol):
    def load_field_dictionary(self) -> FieldDictionary: ...


class SystemConfigProvider(Protocol):
    def load_system_config(self) -> SystemConfig: ...


class Exporter(Protocol):
    def build_case_workbook(
        self,
        *,
        case_id: str,
        dictionary: FieldDictionary,
        results: list[FieldExtractionResult],
    ) -> bytes: ...


class SettingsStatusProvider(Protocol):
    def system_settings_payload(self) -> dict: ...
    def field_dictionary_payload(self) -> dict: ...
    def runtime_settings_payload(self) -> dict: ...
    def validate_settings_payload(self, request: object) -> dict: ...


class MaintenancePort(Protocol):
    def clear_processing_cache(self) -> int: ...
    def clear_all_cases(self) -> int: ...
