"""baseline: capture all 7 tables

Revision ID: 49c3ae9324b2
Revises: 
Create Date: 2026-05-19 23:01:14.282324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49c3ae9324b2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('file_hash', sa.String(length=128), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('raw_document_ir_json', sa.Text(), nullable=True),
    sa.Column('document_ir_json', sa.Text(), nullable=True),
    sa.Column('diagnostics_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cases_case_id'), ['case_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_cases_file_hash'), ['file_hash'], unique=False)

    op.create_table('field_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('field_key', sa.String(length=128), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('reviewed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('field_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_field_results_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_field_results_field_key'), ['field_key'], unique=False)

    op.create_table('processing_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=96), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('config_snapshot_json', sa.Text(), nullable=False),
    sa.Column('quality_json', sa.Text(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('ocr_block_count', sa.Integer(), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('auto_accept_count', sa.Integer(), nullable=False),
    sa.Column('review_required_count', sa.Integer(), nullable=False),
    sa.Column('unknown_count', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('processing_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processing_runs_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_runs_run_id'), ['run_id'], unique=True)

    op.create_table('review_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('field_key', sa.String(length=128), nullable=False),
    sa.Column('before_json', sa.Text(), nullable=False),
    sa.Column('after_json', sa.Text(), nullable=False),
    sa.Column('reviewer', sa.String(length=128), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_audit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_audit_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_audit_field_key'), ['field_key'], unique=False)

    op.create_table('vision_fallback_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=96), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('field_key', sa.String(length=128), nullable=True),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('bbox_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('reviewer', sa.String(length=128), nullable=False),
    sa.Column('manual_redaction_confirmed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vision_fallback_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vision_fallback_requests_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vision_fallback_requests_field_key'), ['field_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_vision_fallback_requests_request_id'), ['request_id'], unique=True)

    op.create_table('model_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.String(length=96), nullable=False),
    sa.Column('run_id', sa.String(length=96), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('stage', sa.String(length=128), nullable=False),
    sa.Column('provider', sa.String(length=128), nullable=False),
    sa.Column('model', sa.String(length=256), nullable=False),
    sa.Column('mode', sa.String(length=128), nullable=False),
    sa.Column('field_keys_json', sa.Text(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('cached_input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('error_code', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('fallback_attempts', sa.Integer(), nullable=False),
    sa.Column('fallback_failures', sa.Integer(), nullable=False),
    sa.Column('fallback_errors_json', sa.Text(), nullable=False),
    sa.Column('llm_cache_status', sa.String(length=64), nullable=True),
    sa.Column('llm_cache_key', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['processing_runs.run_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_calls_call_id'), ['call_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_model_calls_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_calls_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_calls_stage'), ['stage'], unique=False)

    op.create_table('processing_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=96), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('step_name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('error_code', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['processing_runs.run_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('processing_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processing_events_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_events_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_events_step_name'), ['step_name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processing_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processing_events_step_name'))
        batch_op.drop_index(batch_op.f('ix_processing_events_run_id'))
        batch_op.drop_index(batch_op.f('ix_processing_events_case_id'))

    op.drop_table('processing_events')
    with op.batch_alter_table('model_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_calls_stage'))
        batch_op.drop_index(batch_op.f('ix_model_calls_run_id'))
        batch_op.drop_index(batch_op.f('ix_model_calls_case_id'))
        batch_op.drop_index(batch_op.f('ix_model_calls_call_id'))

    op.drop_table('model_calls')
    with op.batch_alter_table('vision_fallback_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vision_fallback_requests_request_id'))
        batch_op.drop_index(batch_op.f('ix_vision_fallback_requests_field_key'))
        batch_op.drop_index(batch_op.f('ix_vision_fallback_requests_case_id'))

    op.drop_table('vision_fallback_requests')
    with op.batch_alter_table('review_audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_audit_field_key'))
        batch_op.drop_index(batch_op.f('ix_review_audit_case_id'))

    op.drop_table('review_audit')
    with op.batch_alter_table('processing_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processing_runs_run_id'))
        batch_op.drop_index(batch_op.f('ix_processing_runs_case_id'))

    op.drop_table('processing_runs')
    with op.batch_alter_table('field_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_field_results_field_key'))
        batch_op.drop_index(batch_op.f('ix_field_results_case_id'))

    op.drop_table('field_results')
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cases_file_hash'))
        batch_op.drop_index(batch_op.f('ix_cases_case_id'))

    op.drop_table('cases')
    # ### end Alembic commands ###
